import type { Metadata } from 'next';
import { Providers } from '@/providers/providers';
import {
  geistSans,
  geistMono,
  inter,
  lusitana,
} from '@/ui/fonts'
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${lusitana.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
